/obj/item/clothing/glasses/thermal/yautja
	name = "bio-mask thermal"
	desc = "A vision overlay generated by the Bio-Mask. Used to sense the heat of prey."
	icon = 'modular_RUtgmc/icons/obj/hunter/pred_gear.dmi'
	icon_state = "visor_thermal"
	item_state = "visor_thermal"
	item_icons = list(
		slot_glasses_str = 'modular_RUtgmc/icons/mob/hunter/pred_gear.dmi'
	)
	vision_flags = SEE_MOBS
	flags_inventory = COVEREYES
	toggleable = FALSE

/obj/item/clothing/glasses/thermal/yautja/Initialize()
	. = ..()
	ADD_TRAIT(src, TRAIT_NODROP, TRAIT_GENERIC)

/obj/item/clothing/glasses/thermal/yautja/dropped(mob/living/carbon/human/user)
	if(istype(user) && user.glasses == src)
		user.clear_fullscreen("machine", 5)
	..()

/obj/item/clothing/glasses/thermal/yautja/equipped(mob/living/carbon/human/user, slot)
	if(slot == SLOT_GLASSES)
		user.overlay_fullscreen("machine", /atom/movable/screen/fullscreen/machine/pred)
	..()

/obj/item/clothing/glasses/thermal/yautja/unequipped(mob/living/carbon/human/user, slot)
	if(slot == SLOT_GLASSES)
		user.clear_fullscreen("machine", 5)
	..()
