// What kind of function to use for Explosions falling off.
#define EXPLOSION_FALLOFF_SHAPE_LINEAR 1
#define EXPLOSION_FALLOFF_SHAPE_EXPONENTIAL 2
#define EXPLOSION_FALLOFF_SHAPE_EXPONENTIAL_HALF 3

#define EXPLOSION_MAX_POWER 5000
