#define PRED_CHARACTER_CUSTOMIZATION 2
#define BACKGROUND_INFORMATION 3
#define GEAR_CUSTOMIZATION 4
#define JOB_PREFERENCES 5
#define GAME_SETTINGS 6
#define KEYBIND_SETTINGS 7
#define DRAW_ORDER 8

#define WIDESCREEN_RESOLUTIONS list(\
	CONFIG_GET(string/default_view1),\
	CONFIG_GET(string/default_view2),\
	CONFIG_GET(string/default_view3)\
	)

#define WIDESCREEN1 "17x15"
#define WIDESCREEN2 "19x15"
#define WIDESCREEN3 "21x15"
#define SQUARESCREEN "15x15"
