/obj/machinery/vending/medical
	products = list(
		"Pill Bottle" = list(
			/obj/item/storage/pill_bottle/bicaridine = 15,
			/obj/item/storage/pill_bottle/kelotane = 15,
			/obj/item/storage/pill_bottle/tramadol = 15,
			/obj/item/storage/pill_bottle/tricordrazine = 15,
			/obj/item/storage/pill_bottle/dylovene = 15,
			/obj/item/storage/pill_bottle/inaprovaline = 15,
			/obj/item/storage/pill_bottle/isotonic = 15,
			/obj/item/storage/pill_bottle/paracetamol = 6,
			/obj/item/storage/pill_bottle/dexalin = 6,
			/obj/item/storage/pill_bottle/spaceacillin = 6,
			/obj/item/storage/pill_bottle/alkysine = 6,
			/obj/item/storage/pill_bottle/imidazoline = 6,
			/obj/item/storage/pill_bottle/quickclot = 6,
			/obj/item/storage/pill_bottle/hypervene = 6,
			/obj/item/storage/pill_bottle/russian_red = 6,
		),
		"Hypospray" = list (
			/obj/item/reagent_containers/hypospray/autoinjector/dexalinplus = 10,
			/obj/item/reagent_containers/hypospray/advanced = 5,
			/obj/item/reagent_containers/hypospray/advanced/bicaridine = 5,
			/obj/item/reagent_containers/hypospray/advanced/kelotane = 5,
			/obj/item/reagent_containers/hypospray/advanced/tramadol = 5,
			/obj/item/reagent_containers/hypospray/advanced/tricordrazine = 5,
			/obj/item/reagent_containers/hypospray/advanced/dylovene = 5,
		),
		"Reagent Bottle" = list(
			/obj/item/reagent_containers/glass/bottle/bicaridine = 6,
			/obj/item/reagent_containers/glass/bottle/kelotane = 6,
			/obj/item/reagent_containers/glass/bottle/tramadol = 6,
			/obj/item/reagent_containers/glass/bottle/tricordrazine = 6,
			/obj/item/reagent_containers/glass/bottle/dylovene = 6,
			/obj/item/reagent_containers/glass/bottle/inaprovaline = 6,
			/obj/item/reagent_containers/glass/bottle/paracetamol = 6,
			/obj/item/reagent_containers/glass/bottle/isotonic = 6,
			/obj/item/reagent_containers/glass/bottle/dexalin = 6,
			/obj/item/reagent_containers/glass/bottle/spaceacillin = 6,
			/obj/item/reagent_containers/glass/bottle/oxycodone = 6,
			/obj/item/reagent_containers/glass/bottle/sleeptoxin = 6,
			/obj/item/reagent_containers/glass/bottle/polyhexanide = 6,
			/obj/item/reagent_containers/glass/bottle/medicalnanites = 12,
		),
		"Chemistry Equipment" = list(
			/obj/item/reagent_containers/syringe = -1,
			/obj/item/reagent_containers/glass/beaker = -1,
			/obj/item/reagent_containers/glass/beaker/large = -1,
			/obj/item/reagent_containers/glass/beaker/vial = -1,
			/obj/item/reagent_containers/dropper = -1,
			/obj/item/storage/reagent_tank = 5,
			/obj/item/storage/reagent_tank/bicaridine = 1,
			/obj/item/storage/reagent_tank/kelotane = 1,
			/obj/item/storage/reagent_tank/tramadol = 1,
			/obj/item/storage/reagent_tank/tricordrazine = 1,
			/obj/item/storage/reagent_tank/bktt = 1,
		),
		"Misc" = list(
			/obj/item/tool/research/xeno_analyzer = -1,
			/obj/item/tool/research/excavation_tool = -1,
			/obj/item/storage/pouch/surgery = -1,
			/obj/item/armor_module/storage/uniform/surgery_webbing = -1,
			/obj/item/reagent_containers/spray/surgery = -1,
			/obj/item/tool/soap = 3,
			/obj/item/clothing/glasses/hud/health = 6,
			/obj/item/roller = 6,
		),
	)

/obj/machinery/vending/medical/valhalla
	products = list(
		"Hypospray" = list (
			/obj/item/reagent_containers/hypospray/autoinjector/dexalinplus = -1,
			/obj/item/reagent_containers/hypospray/advanced = -1,
			/obj/item/reagent_containers/hypospray/advanced/bicaridine = -1,
			/obj/item/reagent_containers/hypospray/advanced/kelotane = -1,
			/obj/item/reagent_containers/hypospray/advanced/tramadol = -1,
			/obj/item/reagent_containers/hypospray/advanced/tricordrazine = -1,
			/obj/item/reagent_containers/hypospray/advanced/dylovene = -1,
		),
		"Reagent Bottle" = list(
			/obj/item/reagent_containers/glass/bottle/bicaridine = -1,
			/obj/item/reagent_containers/glass/bottle/kelotane = -1,
			/obj/item/reagent_containers/glass/bottle/tramadol = -1,
			/obj/item/reagent_containers/glass/bottle/tricordrazine = -1,
			/obj/item/reagent_containers/glass/bottle/dylovene = -1,
			/obj/item/reagent_containers/glass/bottle/inaprovaline = -1,
			/obj/item/reagent_containers/glass/bottle/paracetamol = -1,
			/obj/item/reagent_containers/glass/bottle/isotonic = -1,
			/obj/item/reagent_containers/glass/bottle/sleeptoxin = -1,
			/obj/item/reagent_containers/glass/bottle/spaceacillin = -1,
			/obj/item/reagent_containers/glass/bottle/dexalin = -1,
			/obj/item/reagent_containers/glass/bottle/oxycodone = -1,
			/obj/item/reagent_containers/glass/bottle/polyhexanide = -1,
			/obj/item/reagent_containers/glass/bottle/adminordrazine = -1,
			/obj/item/reagent_containers/glass/bottle/lemoline = -1,
			/obj/item/reagent_containers/glass/bottle/nanoblood = -1,
			/obj/item/reagent_containers/glass/bottle/doctor_delight = -1,
			/obj/item/reagent_containers/glass/bottle/medicalnanites = -1,
		),
		"Pill Bottle" = list(
			/obj/item/storage/pill_bottle/bicaridine = -1,
			/obj/item/storage/pill_bottle/kelotane = -1,
			/obj/item/storage/pill_bottle/tramadol = -1,
			/obj/item/storage/pill_bottle/tricordrazine = -1,
			/obj/item/storage/pill_bottle/dylovene = -1,
			/obj/item/storage/pill_bottle/inaprovaline = -1,
			/obj/item/storage/pill_bottle/isotonic = -1,
			/obj/item/storage/pill_bottle/paracetamol = -1,
			/obj/item/storage/pill_bottle/dexalin = -1,
			/obj/item/storage/pill_bottle/spaceacillin = -1,
			/obj/item/storage/pill_bottle/alkysine = -1,
			/obj/item/storage/pill_bottle/imidazoline = -1,
			/obj/item/storage/pill_bottle/quickclot = -1,
			/obj/item/storage/pill_bottle/hypervene = -1,
			/obj/item/storage/pill_bottle/russian_red = -1,
		),
		"Heal Pack" = list(
			/obj/item/stack/medical/heal_pack/advanced/bruise_pack = -1,
			/obj/item/stack/medical/heal_pack/advanced/burn_pack = -1,
			/obj/item/stack/medical/heal_pack/ointment = -1,
			/obj/item/stack/medical/heal_pack/gauze = -1,
			/obj/item/stack/medical/splint = -1,
		),
		"Misc" = list(
			/obj/item/tool/research/xeno_analyzer = -1,
			/obj/item/tool/research/excavation_tool = -1,
			/obj/item/storage/pouch/surgery = -1,
			/obj/item/armor_module/storage/uniform/surgery_webbing = -1,
			/obj/item/reagent_containers/spray/surgery = -1,
			/obj/item/tool/soap = -1,
			/obj/item/clothing/glasses/hud/health = -1,
			/obj/item/roller = -1,
		),
		"Chemistry Equipment" = list(
			/obj/item/reagent_containers/syringe = -1,
			/obj/item/storage/syringe_case/empty = -1,
			/obj/item/reagent_containers/glass/beaker/bluespace = -1,
			/obj/item/reagent_containers/glass/beaker = -1,
			/obj/item/reagent_containers/glass/beaker/large = -1,
			/obj/item/reagent_containers/glass/beaker/vial = -1,
			/obj/item/reagent_containers/dropper = -1,
			/obj/item/storage/reagent_tank = -1,
			/obj/item/storage/reagent_tank/bicaridine = -1,
			/obj/item/storage/reagent_tank/kelotane = -1,
			/obj/item/storage/reagent_tank/tramadol = -1,
			/obj/item/storage/reagent_tank/tricordrazine = -1,
			/obj/item/storage/reagent_tank/bktt = -1,
		),
		"Valhalla" = list(
			/obj/item/reagent_containers/glass/beaker/bluespace = -1,
			/obj/item/reagent_containers/hypospray/autoinjector/rezadone = -1,
			/obj/item/reagent_containers/hypospray/autoinjector/virilyth = -1,
			/obj/item/reagent_containers/hypospray/autoinjector/roulettium = -1,
			/obj/item/reagent_containers/glass/bottle/toxin = -1,
		),
	)

/obj/machinery/vending/nanomed/tadpolemed
	products = list(
		"Autoinjectors" = list(
			/obj/item/reagent_containers/hypospray/autoinjector/bicaridine = 1,
			/obj/item/reagent_containers/hypospray/autoinjector/kelotane = 1,
			/obj/item/reagent_containers/hypospray/autoinjector/dylovene = 1,
			/obj/item/reagent_containers/hypospray/autoinjector/tricordrazine = 1,
			/obj/item/reagent_containers/hypospray/autoinjector/tramadol = 1,
			/obj/item/reagent_containers/hypospray/autoinjector/combat = 1,
			/obj/item/reagent_containers/hypospray/autoinjector/hypervene = 1,
			/obj/item/reagent_containers/hypospray/autoinjector/inaprovaline = 1,
			/obj/item/reagent_containers/hypospray/autoinjector/dexalinplus = 1,
		),
		"Reagent Bottles" = list(
			/obj/item/reagent_containers/syringe = 10,
			/obj/item/reagent_containers/glass/bottle/dylovene = 1,
			/obj/item/reagent_containers/glass/bottle/bicaridine = 1,
			/obj/item/reagent_containers/glass/bottle/inaprovaline = 1,
			/obj/item/reagent_containers/glass/bottle/spaceacillin = 1,
			/obj/item/reagent_containers/glass/bottle/kelotane = 1,
			/obj/item/reagent_containers/glass/bottle/dexalin = 1,
			/obj/item/reagent_containers/glass/bottle/tramadol = 1,
			/obj/item/reagent_containers/glass/bottle/oxycodone = 1,
			/obj/item/reagent_containers/glass/bottle/polyhexanide = 1,
		),
		"Heal Pack" = list(
			/obj/item/stack/medical/heal_pack/gauze = 2,
			/obj/item/stack/medical/heal_pack/ointment = 2,
			/obj/item/stack/medical/heal_pack/advanced/bruise_pack = 5,
			/obj/item/stack/medical/heal_pack/advanced/burn_pack = 5,
			/obj/item/healthanalyzer = 1,
			/obj/item/stack/medical/splint = 1,
		),
	)
